### PR TITLE
Add ability to use spark reader native implemention

### PR DESCRIPTION
**Pull request by maroil**
Current FileConnector use a customized way of reading file by lister all paths and passing it to Spark.
It is useful but still we need to make it possible for developers to use the "native" way provided by Spark.

This update add an optional flag to read function to make it possible to choose between native reader in spark and the customized one by Setl.

Another way of implementing this is by adding a new parameter to FileConnectorConf.

**EDIT**
I made a change to add a new option in FileConnectorConf

### CODE REVIEW

**Comment by qxzzxq** [comment]
That's a great job :D However, the word `native` seems not explanatory enough. I have an idea, what do you think if we:

1. change the word `native` in variable/parameter names to `useNativeWildcard` (bool value)?
2. or we can change the parameter to `pathFormat`. It will be an optional parameter of type `PathFormat` (which is an enum that has two values: `wildcard` and `regex`). `regex` will be the default value of `pathFormat`.

Personally, I prefer the second one :) What do you think? @maroil @JorisTruong @amauryfournier

**Comment by maroil** [comment]
> That's a great job :D However, the word `native` seems not explanatory enough. I have an idea, what do you think if we:
> 
> 1. change the word `native` in variable/parameter names to `useNativeWildcard` (bool value)?
> 2. or we can change the parameter to `pathFormat`. It will be an optional parameter of type `PathFormat` (which is an enum that has two values: `wildcard` and `regex`). `regex` will be the default value of `pathFormat`.
> 
> Personally, I prefer the second one :) if creating an enum is unnecessary, we can also simply use a string value. What do you think? @maroil @JorisTruong @amauryfournier

I prefer the second one also.
To be sure, regex is the current mechanism and wildcard will be the new (use the native spark reader) ?

**Comment by qxzzxq** [comment]
> > That's a great job :D However, the word `native` seems not explanatory enough. I have an idea, what do you think if we:
> > 
> > 1. change the word `native` in variable/parameter names to `useNativeWildcard` (bool value)?
> > 2. or we can change the parameter to `pathFormat`. It will be an optional parameter of type `PathFormat` (which is an enum that has two values: `wildcard` and `regex`). `regex` will be the default value of `pathFormat`.
> > 
> > Personally, I prefer the second one :) if creating an enum is unnecessary, we can also simply use a string value. What do you think? @maroil @JorisTruong @amauryfournier
> 
> I prefer the second one also.
> To be sure, regex is the current mechanism and wildcard will be the new (use the native spark reader) ?

Yep, currently SETL supports paths with Regex, which will be the default option of `pathFormat`. Spark's reader by default uses wildcard paths. Users will need to explicitly set `pathFormat` to `Wildcard` to use it.

**Comment by maroil** [comment]
@qxzzxq can you review the new implementation ?

**Review by qxzzxq — APPROVED** [review]

**Comment by qxzzxq** [comment]
> @qxzzxq can you review the new implementation ?

Done :D, the new snapshot version will be deployed using the group id `io.github.setl-framework`. Use the following pom configuration

```xml
<repositories>
  <repository>
    <id>ossrh-snapshots</id>
    <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>io.github.setl-framework</groupId>
    <artifactId>setl_2.12</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </dependency>
</dependencies>
```

**Comment by JorisTruong** [comment]
> 
> 
> That's a great job :D However, the word `native` seems not explanatory enough. I have an idea, what do you think if we:
> 
> 1. change the word `native` in variable/parameter names to `useNativeWildcard` (bool value)?
> 
> 2. or we can change the parameter to `pathFormat`. It will be an optional parameter of type `PathFormat` (which is an enum that has two values: `wildcard` and `regex`). `regex` will be the default value of `pathFormat`.
> 
> 
> Personally, I prefer the second one :) if creating an enum is unnecessary, we can also simply use a string value. What do you think? @maroil @JorisTruong @amauryfournier

I also think the second option looks better 😄
Thanks @maroil for the work!

**Pull request merged**
